In [1]:
#SHAGUN 102317057


In [23]:
#ques1
arr1=np.array([2,4,5,6,12])
#1.a)
print(arr1+2)
#1.b)
print(arr1*3)
#1.c)
print(arr1//2)

[ 4  6  7  8 14]
[ 6 12 15 18 36]
[1 2 2 3 6]


In [27]:
#ques2)
#2.a)
import numpy as np
arr=np.array([1,2,3,6,4,5])
arr=arr[::-1]
print(arr)
#2.b)
def most_frequent_values_indices(arr):
    unique, counts = np.unique(arr, return_counts=True)  
    max_count = np.max(counts) 
    most_frequent_values = unique[counts == max_count]  
    indices_dict = {val: np.where(arr == val)[0] for val in most_frequent_values} 
    
    return indices_dict

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])  
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3]) 

result_x = most_frequent_values_indices(x)
result_y = most_frequent_values_indices(y)

print("For array x:")
for value, indices in result_x.items():
    print(f"Most frequent value = {value}, Indices = {indices}")


print("\nFor array y:")
for value, indices in result_y.items():
    print(f"Most frequent value = {value}, Indices = {indices}")


[5 4 6 3 2 1]
For array x:
Most frequent value = 1, Indices = [0 5 7 8 9]

For array y:
Most frequent value = 1, Indices = [0 1 2]
Most frequent value = 3, Indices = [4 8 9]


In [29]:
#ques3)
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

a = arr[0, 1] 
b = arr[2, 0]  

print("Element at 1st row, 2nd column:",a)
print("Element at 3rd row, 1st column:",b)


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [31]:
#ques4)
import numpy as np
shagun = np.linspace(10, 100, 25)

print("Array:", shagun)
print("Dimensions of array:", shagun.ndim)
print("Shape of array:", shagun.shape)
print("Total elements in array:", shagun.size)
print("Data type of each element:", shagun.dtype)
print("Total bytes consumed by the array:", shagun.nbytes)

transpose_array = shagun.reshape(25, 1)
print("\nTranspose using reshape():\n", transpose_array)

print("\nTranspose using T attribute:\n", shagun.T) 


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of array: 1
Shape of array: (25,)
Total elements in array: 25
Data type of each element: float64
Total bytes consumed by the array: 200

Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
#ques5)
import numpy as np

ucs420_shagun = np.array([[10, 20, 30, 40], 
                            [50, 60, 70, 80], 
                            [90, 15, 20, 35]])

mean_value = np.mean(ucs420_shagun)      
median_value = np.median(ucs420_shagun)  
max_value = np.max(ucs420_shagun)        
min_value = np.min(ucs420_shagun)        
unique_elements = np.unique(ucs420_shagun)  

reshaped_ucs420_shagun = ucs420_yourname.reshape(4, 3)

# Resizing to 2 rows and 3 columns (Note: This reduces the number of elements!)
resized_ucs420_yourname = np.resize(ucs420_yourname, (2, 3))

# Printing results
print("Original Array (3x4):\n", ucs420_yourname)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Maximum:", max_value)
print("Minimum:", min_value)
print("Unique Elements:", unique_elements)

print("\nReshaped Array (4x3):\n", reshaped_ucs420_yourname)
print("\nResized Array (2x3):\n", resized_ucs420_yourname)
